<form role="form" method="post">
    <?php $errors = $this->errors->val(); ?>
    
    <?php if (count($errors) > 0): ?>
        <div>
            <p>Please check the following fields:</p>
            <ul>
                <?php foreach ($errors as $error): ?>
                    <li><?= $error; ?></li>
                <?php endforeach; ?>
            </ul>
        </div>
    <?php endif; ?>
    
    <?= $this->elements; ?>
</form>