<div class="form-group">
    <label <?= $this->id->attr(null, 'for'); ?>><?= $this->label; ?></label>
    <?php foreach ((array)$this->options->val() as $value => $label): ?>
        <div class="checkbox">
            <label>
                <input type="checkbox" name="<?= $this->name; ?>[]" id="<?= $this->id . '_' . $value; ?>" value="<?= $value; ?>" <?= $this->checked->prop(in_array($value, (array)$this->value->val())); ?>>
                <?= $label; ?>
            </label>
        </div>
    <?php endforeach; ?>
</div>