<div class="form-group">
    <label <?= $this->id->attr(null, 'for'); ?>><?= $this->label; ?></label>
    <?php foreach ((array)$this->options->val() as $value => $label): ?>
        <div class="radio">
            <label>
                <input type="radio" <?= $this->name->attr(); ?> id="<?= $this->id . '_' . $value; ?>" value="<?= $value; ?>" <?= $this->checked->prop($value === $this->value->val()); ?>>
                <?= $label; ?>
            </label>
        </div>
    <?php endforeach; ?>
</div>